### PR TITLE
Simpler substitutions (not yet ready)

### LINKED ISSUE #20: Reorder premises in rules
And then remove `myptt.v`. This needs to be done carefully as some proof might break.

### PR DESCRIPTION
**Pull request by TheoWinterhalter**
I just open this to indicate that I'm working on the branch **simpler-substitutions**.
It removes annotations from substitutions.

This branch also comes with interesting features:
* `magic` is seriously improved to deal with even more cases,
* this in particular solves the problems of `myptt.v` which can be removed (fix #20).

### CODE REVIEW

**Comment by TheoWinterhalter** [comment]
The magic tactic is pretty close to a type checking algorithm that is specialised in dealing with assumptions and meta-variables.
The handling of substitutions is still somewhat annoying, I would like to systematise it in order to avoid any loop and repetition.

So my question is, wouldn't it be worth it to think a little about how to type check everything in PTT so that we don't have to prove sanity every time?

**Comment by TheoWinterhalter** [comment]
Little update on the status of this branch.
* `magic` has been heavily improved but it is very slow (probably because of all the guess-work induced by non-annotated substitutions—it is often challenging for me as well),
* Sanity and inversion are proved,
* I no longer believe in uniqueness of typing, at least not in uniqueness of substitution codomain.

Let me explain the last point:
If we take two derivations of `σ↑` ending in SubstShift, namely
`σ : Γ → Δ`  and `Δ ⊢ A` give `σ↑ : Γ,A[σ] → Δ,A`  and
`σ : Γ' → Δ'`  and `Δ' ⊢ A'` give `σ↑ : Γ',A'[σ] → Δ',A'`
with `Γ,A[σ] = Γ',A'[σ]`.

We want to prove that `Δ,A = Δ',A'`.
We can indeed prove that `Δ = Δ'` by induction hypothesis and `A[σ] = A'[σ]` by inversion.
However, from this we cannot deduce that `Δ ⊢ A = A'`!

**Comment by andrejbauer** [comment]
Cannot prove, or do you have a counter-example to uniqueness of typing for substitutions?

**Comment by TheoWinterhalter** [comment]
Ok, say you have `{u} : Γ → Γ,A` then, consider the two types
`B := Id A[w] u[w] u[w]` and
`C := Id A[w] u[w] x0` which are well-formed in context `Γ,A`.
We then have (using SubstShift) both
`{u}↑ : Γ,B[{u}] → Γ,A,B` and
`{u}↑ : Γ,C[{u}] → Γ,A,C`.

Now, both `B[{u}]` and `C[{u}]` are equal to `Id A u u`, meaning the domains of `{u}↑` are the same, while the codomain are different.
To instantiate this we can take `Γ` to be empty, `A := Unit` and `u := ⋆`.

**Comment by TheoWinterhalter** [comment]
I also tried to improve the timing and everything, but it doesn't solve all the goals (doing asserts doesn't work well with magic).

**Comment by andrejbauer** [comment]
Would it help if shift carried information abut the type? But that's strange, to have the type annotation without the context in which it makes sense.

**Comment by TheoWinterhalter** [comment]
It might solve it yes, but that would be a bit weird yes.

**Comment by TheoWinterhalter** [comment]
This won't be merged, but should we keep it around in case?

**Pull request closed without merging**
